### ISSUE TITLE
is it able to use 'pirate-roulette' if i have working 'tap' plugin and 'customentity'

### ISSUE THREAD

**Issue by parangee** [nemosrc/pirate-roulette#1]
nemosrc와 nemosource에 있는 파일을 이용해서 tap 플러그인과 customentity는 빌드에 성공했는데 pirate-roulette은 계속 오류가 발생하네요.
혹시 pirate-roulette이 구현이 애초에 안되도록 되어있는 것인가요?

`Error:(158, 51) java: cannot find symbol
  symbol:   method sendTo(java.lang.Iterable<capture#1 of ? extends org.bukkit.entity.Player>)
  location: interface nemo.mc.packet.Packet`

이부분에서 계속 막히네요...
그리고 RoulettePlayer 파일과 RouletteProcess 파일도 비어있어서 애초에 구현이 안되는건지...
감사합니다..

@nemosrc

**Comment by nemosrc** [comment]
Tap 버전이 맞지 않는것 같습니다.
이 코드를 작성할때 Tap의 버전을 마이너하게 계속 바꿔서 정확한 버전을 찾기가 힘듭니다 ㅜㅜ

빌드 성공하시더라도 클라이언트에 CustomEntity 모드가 들어가야합니다!

**Comment by SONIC-14** [comment]
@nemosrc 감사합니다! 혹시 CustomEntity 모드/플러그인 사용중에 종종 ThrownPotion Entity xxxxx has no item! 이라는 오류가 나타나면서 종료되는 문제가 있는데, 왜 발생하는지 도와주실 수 있나요? 단순히 제가 잘못 빌드한 것인가요?

**Comment by jini5012** [comment]
customentity mod는 어디있나요
그리고 제가 초보여서 그런데 pirate-roulette 적용은 어떻게 하나요

**Comment by sonogram10** [comment]
@SONIC-14 커스텀엔티티 모드 개인적으로 배포해주실 수 있나요? 만약 가능하시다면 제 메일로 보내주세요. 제 메일은 sonogram07@gmail.com 입니다
