### ISSUE TITLE
Pirate roulette tap 버전 문의

### ISSUE THREAD

**Issue by jini5012** [nemosrc/pirate-roulette#2]
제가 하면서 tap의 버전 1.2.19를 본적이 없는데 tap 1.2.19는 어디에있나요?

**Comment by patrick-choe** [comment]
(구) tap repository가 사라졌습니다... 못구합니다.

**Comment by jini5012** [comment]
아......

**Comment by jini5012** [comment]
그럼 이슈 닫겠습니다...

**Comment by minejango2** [comment]
https://github.com/dmsghekdzh/tap/releases/tag/1.2.19

정상적인 방법은 아닌거 같긴 한데 있긴 합니다.
우연히 누가 저장해놓은것을 찾았습니다
매우 오래되었지만 지금이라도 관심있으시다면 한번 빌드해서 써보시기 바랍니다.
