### ISSUE TITLE
custom-entity 문의 

### ISSUE THREAD

**Issue by jini5012** [nemosrc/pirate-roulette#3]
제가 tap-1.2.19를 구하긴 했는데요  custom-entity를 못찾겠어요ㅠㅠ custom-entity를 어디서 다운받고 버전이 뭔가요??

**Comment by jini5012** [comment]
제작자님 어떻게 해요ㅠㅠㅠㅠㅠㅠ

**Comment by jini5012** [comment]
아무나 제발 도와주세요
ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by jini5012** [comment]
하 아무도 안도와주네요..........

**Comment by jini5012** [comment]
아 기모 씌ㅣㅣㅣㅣㅣㅣㅣㅣㅣ(실성)

**Comment by jini5012** [comment]
ㄴㅇㄴ
ㅇㄴ
ㅇㄴ

**Comment by jini5012** [comment]
저기요

**Comment by BaeHyeonWoo-1017** [comment]
https://github.com/noonmaru/custom-entity-bukkit

Noonmaru님이 직접 올리신 CustomEntity플러그인 파일입니다. 컴파일은 알아서 하세요.
모드파일은 현재 상황에서는 찾을 수 없습니다.
이슈로 계속 조르지 마세요 이슈 그러라고 있는거 아닙니다.

**Comment by jini5012** [comment]
넵.
